# Generated by Django 2.0.1 on 2018-01-16 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kale', '0002_auto_20180113_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Yoga', 'Yoga'), ('Rockclimbing', 'Rockclimbing'), ('Tango', 'Tango'), ('Freediving', 'Freediving')], default='Yoga', max_length=200, verbose_name='type of event')),
                ('max_cost', models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(6, 0)])),
                ('person_requesting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_requested', to='kale.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90), django.core.validators.DecimalValidator(7, 5)])),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180), django.core.validators.DecimalValidator(8, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='VenueSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=5, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(7, 5)])),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='events_attending', to='kale.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(6, 0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(6, 0)]),
        ),
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_people',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_organizing', to='kale.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_hosting', to='kale.Venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='kale.Venue'),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='event_request_slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_request', to='kale.EventRequest'),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='event_slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='kale.Event'),
        ),
        migrations.AddField(
            model_name='calendarslot',
            name='venue_slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_slot', to='kale.VenueSlot'),
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kale.Location'),
        ),
    ]
