# Generated by Django 2.0.1 on 2018-01-18 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kale', '0003_auto_20180116_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='time_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(5, 2)]),
        ),
        migrations.AlterField(
            model_name='calendarslot',
            name='event_request_slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slots', to='kale.EventRequest'),
        ),
        migrations.AlterField(
            model_name='calendarslot',
            name='event_slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slots', to='kale.Event'),
        ),
        migrations.AlterField(
            model_name='calendarslot',
            name='venue_slots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slots', to='kale.VenueSlot'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', to='kale.Person'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90), django.core.validators.DecimalValidator(7, 5)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180), django.core.validators.DecimalValidator(8, 5)]),
        ),
    ]
