# Generated by Django 2.0.1 on 2018-01-19 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kale', '0004_auto_20180118_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrequest',
            old_name='category',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='time_cost',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='travel_time_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(5, 2)], verbose_name='cost of time spent travelling (in mins)'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='travel_types',
            field=models.CharField(choices=[('Rideshare', 'Rideshare'), ('Walk', 'Walk'), ('Cycle', 'Cycle'), ('Public Transport', 'Public Transport'), ('Drive', 'Drive')], default='Rideshare', max_length=200, verbose_name='travel options'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='max_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(6, 0)], verbose_name='maximum cost of the event (including travelling)'),
        ),
    ]
